saptamana4/proiect/aplicatie1/urls.py
from django.urls import path

from aplicatie1 import views

app_name = 'locations'

urlpatterns = [

    path('', views.LocationsView.as_view(), name='lista_locatii'),
    path('adaugare/', views.CreateLocationView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateLocationView.as_view(), name='modifica'),
    path('<int:pk>/stergere/', views.delete_location, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_location, name='activeaza'),



]

saptamana4/proiect/aplicatie2/urls.py
from django.urls import path

from aplicatie2 import views

app_name = 'companies'

urlpatterns = [

    path('', views.CompaniesView.as_view(), name='lista_companii'),




]

saptamana4/proiect/myapi/urls.py
from django.urls import include, path
from rest_framework import routers

from myapi import views

router = routers.DefaultRouter()
router.register('location', views.LocationViewSet)

urlpatterns = [
    path('', include(router.urls))
]

saptamana4/proiect/proiectFinal/proiectFinal/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

saptamana4/proiect/proiectFinal/appjob/models.py
from django.db import models

# Create your models here.

saptamana4/proiect/proiectFinal/appjob/views.py
from django.shortcuts import render

# Create your views here.

saptamana4/proiect/templates/aplicatie1/locations_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }}<br>
        {% endfor %}
        <button type="submit">Salveaza</button>
    </form>
{% endblock %}

saptamana4/proiect/templates/aplicatie1/locations_index.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'locations:adauga' %}" class="btn btn-success">Adauga locatie</a>
    <br>
    <table class="table">
        <thead>
        <tr>
            <th>Index</th>
            <th>City</th>
            <th>Country</th>
            <th>Stare</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for item in locations_list %}
            <tr>
                <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
                <td>{{ item.city }}</td>
                <td>{{ item.country }}</td>
                <td>
                <td>{% if item.active == 1 %}
                    <span>Activ</span>
                {% else %}
                    <span>Inactiv</span>
                {% endif %}
                </td>

                <td>
                    <a href="{% url 'locations:modifica' item.id %}" class="btn btn-success">Modifica</a>
                    {% if item.active == 1 %}
                        <a href="{% url 'locations:sterge' item.id %}" class="btn btn-danger">Sterge</a>
                    {% else %}
                        <a href="{% url 'locations:activeaza' item.id %}" class="btn btn-info">Activeaza</a>
                    {% endif %}


                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a class="btn" href="?" page={{ page_obj.previous_page_number }}><<</a></li>
            {% else %}
                <li class="disabled btn"><span><<</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active btn btn-info"><span>{{ i }}<span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a class="btn" href="?" page={{ page_obj.next_page_number }}>>></a></li>
            {% else %}
                <li class="disabled btn"><span>>></span></li>
            {% endif %}
            <span class="align-right">Showing {{ page_obj.start_index }} - {{ page_obj.end_index }} of
            {{ page_obj.paginator.count }}
        </span>
        </ul>
    {% endif %}
{% endblock %}

saptamana4/proiect/templates/aplicatie2/companies_index.html
{% extends 'base.html' %}
{% block content %}
 <a href="{% url 'locations:adauga' %}" class="btn btn-success">Adauga locatie</a>
    <br>
    <table class="table">
        <thead>
        <tr>
            <th>Index</th>
            <th>Nume</th>
            <th>Website</th>
            <th>Tip Companie</th>
            <th>Stare</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for item in locations_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.city }}</td>
                <td>{{ item.country }}</td>
                <td>
                <td>{% if item.active == 1 %}
                    <span>Activ</span>
                {% else %}
                    <span>Inactiv</span>
                {% endif %}
                </td>

                <td>
                    <a href="{% url 'locations:modifica' item.id %}" class="btn btn-success">Modifica</a>
                    {% if item.active == 1 %}
                        <a href="{% url 'locations:sterge' item.id %}" class="btn btn-danger">Sterge</a>
                    {% else %}
                        <a href="{% url 'locations:activeaza' item.id %}" class="btn btn-info">Activeaza</a>
                    {% endif %}


                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

saptamana4/proiect/templates/base.html
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav>
                <a class="btn" href="/admin">Admin</a>
                {% if request.user.is_authenticated %}
                    <a class="btn" href="{% url 'locations:lista_locatii' %}">Locatii</a>
                    <a class="btn" href="{% url 'logout' %}">Logout</a>
                    <span> Hi, {{ request.user.username|upper }} </span>
                    {%  if ready_to_work is False %}
                    <a href="{% url 'userprofile:stop_pontaj' %}" class="btn btn-danger">Oprire pontaj</a>
                        {% else %}
                    <a href="{% url 'userprofile:start_pontaj' %}" class="btn btn-success">Pornire pontaj</a>
                        {% endif %}
                {% endif %}
            </nav>
        </div>
    </div>
</div>
<div class="col-md-12">
{% block content %}
{% endblock %}
</div>
</body>

</html>