saptamana4/proiectfinal/appjob/urls.py
from django.urls import path

from appjob import views

app_name = 'jobs'

urlpatterns = [
    path('', views.JobsViews.as_view(), name='lista_joburi'),
    path('adaugare/', views.CreateJobsView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateJobsView.as_view(), name='modifica'),
    path('<int:pk>/stergere/', views.delete_job, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_job, name='activeaza'),
]

saptamana4/proiectfinal/proiectfinal/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('jobs/', include('appjob.urls')),
    path('profile/', include('user_profile.urls')),
]

saptamana4/proiectfinal/user_profile/urls.py
from django.urls import path

from user_profile import views

app_name = 'userprofile'

urlpatterns = [
    path('start_timesheet/', views.new_timesheet, name ='start_pontaj'),
    path('stop_timesheet/', views.stop_timesheet, name='stop_pontaj'),
]

saptamana4/proiectfinal/appjob/models.py
from django.db import models


class Jobs(models.Model):
    tip_job = models.CharField(max_length=11)
    url_job = models.CharField(max_length=100)
    title_job = models.CharField(max_length=100)
    description_job = models.TextField(blank=True)
    how_to_apply = models.TextField(blank=True)
    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.tip_job} - {self.url_job}"

saptamana4/proiectfinal/user_profile/models.py
from django.db import models


class Logs(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    action = models.CharField(max_length=10)
    url = models.CharField(max_length=100)


class Pontaj(models.Model):
    user = models.ForeignKey('auth.user', on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(null=True)

saptamana4/proiectfinal/appjob/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from appjob.models import Jobs


class JobsViews(LoginRequiredMixin, ListView):
    model = Jobs
    template_name = 'appjob/jobs_index.html'
    paginate_by = 3


class CreateJobsView(LoginRequiredMixin, CreateView):
    model = Jobs
    fields = ['tip_job', 'url_job', 'title_job', 'description_job', 'how_to_apply']
    template_name = 'appjob/jobs_form.html'

    def get_success_url(self):
        return reverse('jobs:lista_joburi')


class UpdateJobsView(LoginRequiredMixin, UpdateView):
    model = Jobs
    fields = ['tip_job', 'url_job', 'title_job', 'description_job', 'how_to_apply']
    template_name = 'appjob/jobs_form.html'

    def get_success_url(self):
        return reverse('jobs:lista_joburi')


@login_required
def delete_job(request, pk):
    Jobs.objects.filter(id=pk).update(active=0)
    return redirect('jobs:lista_joburi')


@login_required
def activate_job(request, pk):
    Jobs.objects.filter(id=pk).update(active=1)
    return redirect('jobs:lista_joburi')

saptamana4/proiectfinal/user_profile/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

from user_profile.models import Pontaj


@login_required
def new_timesheet(request):
    Pontaj.objects.create(user_id=request.user.id, start_date=datetime.datetime.now())
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def stop_timesheet(request):
    Pontaj.objects.filter(user_id=request.user.id, end_date=None).update(end_date=datetime.datetime.now())
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

saptamana4/proiectfinal/templates/appjob/jobs_form.html
{% extends 'base.html' %}
{% block content %}

    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }}<br>
        {% endfor %}
        <button type="submit">Salveaza</button>

    </form>



{% endblock %}

saptamana4/proiectfinal/templates/appjob/jobs_index.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'jobs:adauga' %}" class="btn btn-success">Adauga joburi</a>
    <br>
    <table class="table">
        <thead>
        <tr>
            <th>Index</th>
            <th>Job Type</th>
            <th>URL</th>
            <th>Title</th>
            <th>Description</th>
            <th>How to apply</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for item in jobs_list %}
            <tr>
                <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
                <td>{{ item.tip_job }}</td>
                <td>{{ item.url_job }}</td>
                <td>{{ item.title_job }}</td>
                <td>{{ item.description_job }}</td>
                <td>{{ item.how_to_apply }}</td>
                <td>{% if item.active == 1 %}
                    <span>Activ</span>
                {% else %}
                    <span>Inactiv</span>
                {% endif %}
                </td>

                <td>
                    <a href="{% url 'jobs:modifica' item.id %}" class="btn btn-success">Modifica</a>
                    {% if item.active == 1 %}
                        <a href="{% url 'jobs:sterge' item.id %}" class="btn btn-danger">Sterge</a>
                    {% else %}
                        <a href="{% url 'jobs:activeaza' item.id %}" class="btn btn-info">Post Job</a>
                    {% endif %}

                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="d-flex justify-content-center">
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a class="btn" href="?page={{ page_obj.previous_page_number }}"><<</a></li>
                {% else %}
                    <li class="disabled btn"><span><<</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active btn btn-info"><span>{{ i }}<span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a class="btn" href="?page={{ page_obj.next_page_number }}">>></a></li>
                {% else %}
                    <li class="disabled btn"><span>>></span></li>
                {% endif %}
                <span class="align-right">Showing {{ page_obj.start_index }}-{{ page_obj.end_index }} of {{ page_obj.paginator.count }}</span>
            </ul>
        {% endif %}
    </div>
{% endblock %}

saptamana4/proiectfinal/templates/base.html
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav>
                <a class="btn" href="/admin">Admin</a>
                {% if request.user.is_authenticated %}
                    <a class="btn" href={% url 'jobs:lista_joburi' %}>Joburi</a>
                    <a class="btn" href="{% url 'logout' %}">Logout</a>
                    <span>Hello {{ request.user.username|upper }}</span>
                    {% if ready_to_work is False %}
                    <a href="{% url 'userprofile:stop_pontaj' %}" class="btn btn-danger">Stop Pontaj</a>
                        {% else %}
                    <a href="{% url 'userprofile:start_pontaj' %}" class="btn btn-success">Start Pontaj</a>
                        {% endif %}





                {% endif %}
            </nav>
        </div>
    </div>
</div>
<div class="col-md-12">
    {% block content %}
    {% endblock %}
</div>
</body>

</html>